### ISSUE TITLE
freertos-drivers - close source?

### ISSUE THREAD

**Issue by mgiaco** [braiins/micropython-demo-ecu#1]
Is the freertos lib and stuff you have used closed source?

many thanks
cheers
mathias

**Comment by janbraiins** [comment]
Nope, it just hasn't been released. I want to reorganize a few things
before releasing it. I can do it sooner if you are interested

**Comment by mgiaco** [comment]
Hi, that sounds really great. Yes I am very interested after I have seen your presentation.

**Comment by mgiaco** [comment]
Hi, do you have any news here?

**Comment by mgiaco** [comment]
Any news here?
